### ISSUE TITLE
Improvements for Usability

### ISSUE THREAD

**Issue by bipinkrish** [sign-language-processing/pose#116]
Are you open to export `PoseViewer` class in https://github.com/sign-language-processing/pose/blob/master/src/js/pose_viewer/src/index.ts so that that can be used as a component in different frameworks, currently only `Components` namespace is exported

**Comment by AmitMY** [comment]
Sure. if that helps you, please export it.
The reason it is not exported, is that the moment you use a `pose-viewer` element, you can then just access it from the DOM and that allows you access to the class instance

**Comment by bipinkrish** [comment]
@AmitMY above PR solves it
