### ISSUE TITLE
is this the accurate representation of specs?

### ISSUE THREAD

**Issue by bipinkrish** [sign-language-processing/pose#121]
according to https://github.com/sign-language-processing/pose/blob/master/docs/specs/v0.2.md is this valid representation?

```
┌──────────────────────────┐
│         HEADER           │
├──────────────────────────┤
│ Version       (4 bytes)  │
│ Width         (2 bytes)  │
│ Height        (2 bytes)  │
│ Depth         (2 bytes)  │
│ Num Components (2 bytes) │
├──────────────────────────┤
│     COMPONENTS DATA      │
├──────────────────────────┤
│ Component 1              │
│  ├─ Name    (var bytes)  │
│  ├─ Format  (var bytes)  │
│  ├─ Num Points (2 bytes) │
│  ├─ Num Limbs  (2 bytes) │
│  └─ Num Colors (2 bytes) │
│    ├─ Points Data        │
│    ├─ Limbs Data         │
│    └─ Colors Data        │
├──────────────────────────┤
│ Component 2...N          │
├──────────────────────────┤
│         BODY             │
├──────────────────────────┤
│ FPS           (4 bytes)  │
│ Num Frames    (2 bytes)  │
│ Num People    (2 bytes)  │
├──────────────────────────┤
│     POSITION DATA        │
│ Frame 1                  │
│  ├─ Person 1             │
│  │   ├─ Component 1      │
│  │   │  ├─ X (4 bytes)   │
│  │   │  └─ Y (4 bytes)   │
│  │   └─ Component 2..N   │
│  └─ Person 2..M          │
├──────────────────────────┤
│     CONFIDENCE DATA      │
│ Frame 1                  │
│  ├─ Person 1             │
│  │   ├─ Component 1      │
│  │   │  └─ Conf(4 bytes) │
│  │   └─ Component 2..N   │
│  └─ Person 2..M          │
└──────────────────────────┘
```

1. String fields are variable length (null-terminated)
2. The total file size will depend on:
    - Number of components (N)
    - Number of points per component (P)
    - Number of limbs per component (L)
    - Number of colors per component (C)
    - Number of frames (F)
    - Number of people (M)
    - Length of strings (variable)

**Comment by AmitMY** [comment]
I love how you visualized it, a few notes:
1. I think that just specifying the number of bytes can be confusing - need to specify the type as well (float, int, etc)
2. points data is (string x number of points), limbs is ((ushort, ushort) x number of limbs) and colors is ((ushort, ushort, ushort) x number of colors)
3. Body "Num Frames" is unsigned int (so 4 bytes)
4. In position data and confidence, it goes Frame -> Person -> Point (not component)
5. There can be more than just XY, there can be Z, etc... This is specified in "format" of the component ("XYC") is X+Y+ confidence for example

**Comment by bipinkrish** [comment]
```
┌─────────────────────────────────┐
│            HEADER               │
├─────────────────────────────────┤
│ Version       (float, 4B)       │
│ Width         (ushort, 2B)      │
│ Height        (ushort, 2B)      │
│ Depth         (ushort, 2B)      │
│ Num Components (ushort, 2B)     │
├─────────────────────────────────┤
│         COMPONENTS DATA         │
├─────────────────────────────────┤
│ Component 1                     │
│  ├─ Name    (string, var)       │
│  ├─ Format  (string, var)       │
│  ├─ Num Points (ushort, 2B)     │
│  ├─ Num Limbs  (ushort, 2B)     │
│  └─ Num Colors (ushort, 2B)     │
│    ├─ Points Data               │
│    │  └─ [string] × Num Points  │
│    ├─ Limbs Data                │
│    │  └─ [(ushort,ushort)]      │
│    │     × Num Limbs            │
│    └─ Colors Data               │
│       └─ [(ushort,ushort,       │
│           ushort)] × Num Colors │
├─────────────────────────────────┤
│ Component 2...N                 │
├─────────────────────────────────┤
│            BODY                 │
├─────────────────────────────────┤
│ FPS           (float, 4B)       │
│ Num Frames    (uint, 4B)        │
│ Num People    (ushort, 2B)      │
├─────────────────────────────────┤
│         POSITION DATA           │
│ Frame 1                         │
│  ├─ Person 1                    │
│  │   ├─ Point 1                 │
│  │   │  └─ Values based on      │
│  │   │     Format (float, 4B    │
│  │   │     per value)           │
│  │   └─ Point 2..N              │
│  └─ Person 2..M                 │
├─────────────────────────────────┤
│        CONFIDENCE DATA          │
│ Frame 1                         │
│  ├─ Person 1                    │
│  │   ├─ Point 1                 │
│  │   │  └─ Conf (float, 4B)     │
│  │   └─ Point 2..N              │
│  └─ Person 2..M                 │
└─────────────────────────────────┘
```

@AmitMY  is this right?

**Comment by AmitMY** [comment]
To the best of my reading, yes, this is now exactly correct.

**Comment by bipinkrish** [comment]
@AmitMY okay so I have 2 questions,

1. Only change from `v0.1` to `v0.2` is floating value for `FPS`?
2. Is there a plan to store multiple pose data in one file, one advantage i see is merging of multiple pose file into one file enabling easy share?

**Comment by bipinkrish** [comment]
```mermaid
classDiagram
    class Header {
        +float version
        +ushort width
        +ushort height
        +ushort depth
        +ushort numComponents
    }
    
    class Component {
        +string name
        +string format
        +ushort numPoints
        +ushort numLimbs
        +ushort numColors
        +string[] pointNames
        +Limb[] limbs
        +Color[] colors
    }
    
    class Limb {
        +ushort fromPointIndex
        +ushort toPointIndex
    }
    
    class Color {
        +ushort red
        +ushort green
        +ushort blue
    }
    
    class Body {
        +float fps
        +uint numFrames
        +ushort numPeople
    }

    Header "1" -- "*" Component
    Component "1" -- "*" Limb
    Component "1" -- "*" Color
```

```mermaid
    graph TD
    A[File] --> B[Header]
    A --> C[Components Data]
    A --> D[Body]
    A --> E[Position Data]
    A --> F[Confidence Data]
    
    C --> C1[Component 1]
    C --> C2[Component 2]
    C --> CN[Component N]
    
    C1 --> P1[Points Data]
    C1 --> L1[Limbs Data]
    C1 --> CO1[Colors Data]
    
    E --> FR1[Frame 1]
    E --> FR2[Frame 2]
    E --> FRN[Frame N]
    
    FR1 --> PE1[Person 1]
    FR1 --> PE2[Person 2]
    FR1 --> PEN[Person M]
    
    PE1 --> PT1[Point 1 Values]
    PE1 --> PT2[Point 2 Values]
    PE1 --> PTN[Point N Values]
```

```mermaid
    graph LR
    A[Format String] --> B[X]
    A --> C[Y]
    A --> D[Z]
    A --> E[C]
    
    B -->|4 bytes| F[X Position]
    C -->|4 bytes| G[Y Position]
    D -->|4 bytes| H[Z Position]
    E -->|4 bytes| I[Confidence]
```

**Comment by AmitMY** [comment]
1. num frames also changed to uint from ushort
2. the format tries to do two things: be visualized easily, and be shared easily, therefore, if you want to store multiple pose data in one file, you can:
  - a. use the "people" dimension - it is usually just "1" person, but you can stack as many people as you want
  - b. use the "components" - if you want to run let's say `holistic`, and `openpose`, and `sapiens` etc, you can just add "components" to the header, then you can store more data about an individual.

If you have a different use case, we can see :) But for now, best thing for sharing many files, is zipping them. When reading poses, with  a recent update, it knows how to skip the header for fast reading https://github.com/sign-language-processing/pose/commit/9ede7cdc6d5d25cad00ac91c32b2327440f72ae1
And if you wanted to just store the body because you have a specific storage issue (although the header is tiny) you can call `pose.body.write(f)` which will write a file only for the body, but then there won't be support for reading based on components etc.

**Comment by bipinkrish** [comment]
> * a. use the "people" dimension - it is usually just "1" person, but you can stack as many people as you want

if we add more people, then visualize doesn't it bring all people in the same frame?

**Comment by AmitMY** [comment]
When stacking people you have the "choice" between visual coherence and data sharing:

Use case 1: Video with multiple people
When you have multiple people in the frame, they won't overlap. In this video there are 3 people, all showing in all frames, so it makes sense to use the people dimension
![image](https://github.com/user-attachments/assets/6ef5409c-2502-457d-8cd3-70d76e5a1928)

Use case 2: Multiple videos with the same duration
When you have multiple videos with the same duration, you could stack the videos in the people dimension, but they will likely overlap.

**Comment by bipinkrish** [comment]
Okay thank you for explaining
