### ISSUE TITLE
Feature request: DTW-nMJE for pose sequence comparisons

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/pose#123]
As described in https://rotem-shalev.github.io/ham-to-pose/, the capability to calculate distances between two pose sequences. 

I imagine it used something like:
```
from pose_format import Pose
from pathlib import Path()

pose_1_path = Path("file.pose")
pose_2_path = Path("file2.pose")
pose_1 = Pose.read(pose_1_path.open("rb"))
pose_2 = Pose.read(pose_2_path.open("rb"))

distance = pose_1.normalized_dtw_mje(pose2)

# or perhaps something like
distance = pose_1.dtw_mje(pose2, normalized=True)
```

I intend to use something like this for quantifying how visually similar different sign videos are, I figured it might make sense to include in the library itself. 

Ham2Pose implements it with `fastdtw`, see https://github.com/rotem-shalev/Ham2Pose/blob/main/metrics.py#L129

One potential downside would be that it would bloat the requirements of the library due to dependence on fastdtw.

**Comment by J22Melody** [comment]
We are systematically reviewing pose-to-pose metrics under MT context, including the ones borrowed from ham2pose:

https://github.com/rotem-shalev/Ham2Pose/blob/main/metrics.py

Some adaptations need to be made there for more generic purposes, for example, the original code from ham2pose assumes openpose keypoints.

If you would like to contribute to this end, we can talk.

> One potential downside would be that it would bloat the requirements of the library due to dependence on fastdtw.

@AmitMY ^

**Comment by cleong110** [comment]
@J22Melody I'd be interested in contributing, yeah! At the very least I'd like to try and get the ham2pose code converted over to work with the default outputs from `video_to_pose`, because I'd like to test such distance metrics for retrieval

**Comment by AmitMY** [comment]
Cool, so please talk and see how we can push it forward!

As for "where" the metrics are hosted - I vote *against* hosting them in this repository.
I think there are plenty of `.pose` use cases that do not require metrics, so a `pose-evaluation` repository can be opened with the relevant code. happy to open one under `sign-language-processing` and give you both maintainer privileges

**Comment by cleong110** [comment]
That sounds quite sensible to me! A pose-evaluation repo makes more sense than incorporating it in the format repo itself

**Comment by cleong110** [comment]
Seems like we agree this is not the place for this feature! Closing now, we can implement this in some other repo at a later date

**Comment by AmitMY** [comment]
I made a quick repo for pose-evaluation https://github.com/sign-language-processing/pose-evaluation
see slack for more details
