### ISSUE TITLE
Create a new release with latest recursion/multiprocessing features.

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/pose#133]
As mentioned in #132 , we've added some new features lately, and it would be nice to publish those to pypi such that they can be included when one does `pip install pose-format`

**Comment by AmitMY** [comment]
Made it easy. now when I create a github release, it pushes to PyPi
https://github.com/sign-language-processing/pose/commit/f3784600dc66141ec5d94855af2f7a4c0fba6cea
