### ISSUE TITLE
bug: videos_to_poses crash cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'VideoCapture'

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/pose#135]
https://github.com/sign-language-processing/pose/blob/d384d887ff4abaecec7f70fce9ad11b6a05aab94/src/python/pose_format/bin/pose_estimation.py#L21 This line expects a string. But our latest version installed from source [gives it a pathlib Path here](https://github.com/sign-language-processing/pose/blob/master/src/python/pose_format/bin/directory.py#L94).

Propose fix, cast to `str`. Change this:
```
            pose_video(vid_path, pose_path, pose_format, additional_config, progress=False) 
```
To this:
```
            pose_video(str(vid_path), str(pose_path), pose_format, additional_config, progress=False) 
```

Step to replicate:
1. Colab notebook
2. clone repo
3. navigate to the python folder, something like `%cd /content/pose/src/python`
4. !pip install vidgear mediapipe psutil numpy scipy tqdm "opencv-python==4.5.5.64"
5. !pip install -e. # should output something like install pose-format 0.7
6. also installthe other deps, 
7. upload a .mp4 file
8. !videos_to_poses -d directory_containing_the_file

Edit: Here's the traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/content/pose/src/python/pose_format/bin/directory.py", line 94, in process_video
    pose_video(vid_path, pose_path, pose_format, additional_config, progress=False)
  File "/content/pose/src/python/pose_format/bin/pose_estimation.py", line 21, in pose_video
    cap = cv2.VideoCapture(input_path)
cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'VideoCapture'
> Overload resolution failed:
>  - Can't convert object to 'str' for 'filename'
>  - VideoCapture() missing required argument 'apiPreference' (pos 2)
>  - Argument 'index' is required to be an integer
>  - VideoCapture() missing required argument 'apiPreference' (pos 2)
```

**Comment by AmitMY** [comment]
fair point! feel free to make that tiny PR :)

**Comment by cleong110** [comment]
Looking into it further, it seems this was fixed in later versions of OpenCV-Python. 

* https://github.com/opencv/opencv/pull/24773
* https://github.com/opencv/opencv/issues/15731 

So another solution would be to update our requirements to use newer opencv. 

But I'll go ahead and do the tiny PR anyway.

**Comment by AmitMY** [comment]
Yes, at some point we had an issue with a new version of opencv, so had to fix the version to something that worked.
Thanks for the fix!
