### ISSUE TITLE
3D hand normalization with empty frames

### ISSUE THREAD

**Issue by J22Melody** [sign-language-processing/pose#40]
I am trying the code from https://github.com/sign-language-processing/pose/pull/36.

When I input a .pose file where the first few frames are empty (=no right hand detected and all values are 0s), normalization output becomes all nans, where 0s are expected.

Since the pose data is a masked array, I use `pose.body.data.toflex()` to inspect the arrays and now I have to use `np.nan_to_num(pose.body.data)` as a workaround to convert the nans back to 0s.

@AmitMY maybe worth checking the 0-handing logic in the code?

**Comment by AmitMY** [comment]
I'll need to see a reproduction.
In any case, the correct way to get the value from a masked array is `pose.body.data.filled(0)`

**Comment by J22Melody** [comment]
https://colab.research.google.com/drive/1XyfAoKeTDRakiCHYEFgsEoceciaIlsar
