### ISSUE TITLE
Newest pypi version fails for library imports

### ISSUE THREAD

**Issue by bricksdont** [sign-language-processing/pose#41]
The newest version from pypi (0.2.1) still fails when importing something from the library as shown in the documentation:

```python
! pip install pose-format
(...)
Successfully installed pose-format-0.2.1

from pose_format.python.pose import Pose

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-2-61d49156e576>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from pose_format.python.pose import Pose

ModuleNotFoundError: No module named 'pose_format.python'
```

Colab to reproduce:

https://colab.research.google.com/drive/1DNIdkPkQdVb6uedSx37HPZIWgLQr6END?usp=sharing

**Comment by AmitMY** [comment]
In this case, it is the documentation that is wrong (probably changed automatically, and I didn't notice)

It should be:
```py
from pose_format.pose import Pose
```

We should revert the README on this.

**Comment by AmitMY** [comment]
Fixed in https://github.com/sign-language-processing/pose/commit/737a887090de193b21f158743dd3bd906fb430a9
