### ISSUE TITLE
No module named 'pose_format.bin.bin'

### ISSUE THREAD

**Issue by MuhammadAasharibNawshad** [sign-language-processing/pose#75]
When i run this command 
`videos_to_poses --format mediapipe --directory /test_videos`

I get error ModuleNotFoundError: No module named 'pose_format.bin.bin'

I installed the pose_format package using this command `pip install pose_format` i am using latest version i.e.0.3.2

**Comment by AmitMY** [comment]
Thanks for raising this issue.
Resolved in https://github.com/sign-language-processing/pose/commit/106cae4c2ef1e7cd93d63509414d57a97964c4a6
