### ISSUE TITLE
More Documentation for Dart implementation

### ISSUE THREAD

**Issue by bipinkrish** [sign-language-processing/pose#77]
I want to rewrite this in `dart`, is there a guide on the structure and rules of the format?

**Comment by AmitMY** [comment]
You can find the exact data spec for the `.pose` format here: https://github.com/sign-language-processing/pose/blob/master/docs/specs/v0.1.md

The important thing is that you have three classes in your dart implementation:
`Pose`, `PoseHeader` and `PoseBody`

To read it in python, we use:
1. `Pose` https://github.com/sign-language-processing/pose/blob/master/src/python/pose_format/pose.py#L33
2. `PoseHeader` https://github.com/sign-language-processing/pose/blob/master/src/python/pose_format/pose_header.py#L258
3. `PoseBody` https://github.com/sign-language-processing/pose/blob/master/src/python/pose_format/pose_body.py#L89

To read it in javascript, we use https://github.com/sign-language-processing/pose/blob/master/src/js/pose_format/src/parser.ts

If you would like to contribute your implementation, please create a PR under a `src/dart` directory. If you would include tests, it would ensure that we do not introduce breaking changes in the future.

**Comment by bipinkrish** [comment]
> You can find the exact data spec for the `.pose` format here: [`master`/docs/specs/v0.1.md](https://github.com/sign-language-processing/pose/blob/master/docs/specs/v0.1.md?rgh-link-date=2024-02-18T09%3A00%3A17Z)

thanks.

> The important thing is that you have three classes in your dart implementation:
> `Pose`, `PoseHeader` and `PoseBody`

i figured, but was stuck in understanding 

* `BufferReader` https://github.com/sign-language-processing/pose/blob/master/src/python/pose_format/utils/reader.py#L34

since there is no `Struct` data structure in `dart`

> To read it in javascript, we use [`master`/src/js/pose_format/src/parser.ts](https://github.com/sign-language-processing/pose/blob/master/src/js/pose_format/src/parser.ts?rgh-link-date=2024-02-18T09%3A00%3A17Z)

I think `ts` is easier to understand here

> please create a PR under a `src/dart` directory

Ok will do it after completing.

**Comment by bipinkrish** [comment]
*Update* : I was able to load the files, https://pub.dev/packages/pose

**Comment by AmitMY** [comment]
That is great! Thanks for the update.
Feel free to create a pull request that adds dart support and documentation :)

**Comment by bipinkrish** [comment]
*Update* : https://github.com/bipinkrish/pose, Pose to GIF is now possible

**Comment by AmitMY** [comment]
Looks great!

**Comment by bipinkrish** [comment]
I will re-open this once I get time continue
