### ISSUE TITLE
Failed to detect hands using holistic

### ISSUE THREAD

**Issue by pcc03** [sign-language-processing/pose#78]
Hi,

Thanks for you great work! But I encountered one problem when I use my customized video which only has hands instead of whole body. I found that using the video-to-pose, the hands' landmarks cannot be detected and the "pose.body.data" is empty. Could you please let me know how can I modify the code to detect poses for video with hands only?

**Comment by AmitMY** [comment]
Hi there! the `video-to-pose` is intended for full body pose estimation.
For anything else, like hands only, please see MediaPipe's documentation https://developers.google.com/mediapipe/solutions/vision/hand_landmarker

You could use their hand landmarker, along with our [hand components](https://github.com/sign-language-processing/pose/blob/master/src/python/pose_format/utils/holistic.py#L270) to create a pose object that is compatible with this library

**Comment by pcc03** [comment]
Thank you! I have modified the pose object and now it's compatible with the library now!
