### ISSUE TITLE
video_to_pose: command not found

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/pose#79]
Followed the instructions on the Readme, installed the library and then tried running the `video_to_pose` command, only for it to be "not found". 

```
conda create -n pose-format pip 
conda activate pose-format
python -m pip install pose-format
$ video_to_pose
video_to_pose: command not found
```

Perhaps it might be a legacy item from the deprecated https://github.com/sign-language-processing/transcription? Which does have a folder/module of that name.

**Comment by cleong110** [comment]
creating an env for https://github.com/sign-language-processing/transcription seems to confirm that when you install _that_ it does indeed contain such a `video_to_pose` command

**Comment by cleong110** [comment]
Aha! that works! Now I get "no module named 'cv2'" but of course you can solve that with `python -m pip install opencv-python`

**Comment by cleong110** [comment]
... and `python -m pip install mediapipe`

**Comment by AmitMY** [comment]
Thanks for confirming.
Yes, they are in dev dependencies because they are not needed for just using pose files, and opencv is a very large library (ideally, just loading and saving files should be very lightweight)
Perhaps we can improve the error messages in the future
![image](https://github.com/sign-language-processing/pose/assets/5757359/114266ee-5f43-4500-a092-f8262c36b886)

**Comment by SalsabilRefaei** [comment]
It gives me an AttributeError when I try the following:
videos_to_poses --format mediapipe --directory path/to/my/directory
  
  
![image](https://github.com/sign-language-processing/pose/assets/139865772/ef2ab33a-fe60-4497-8bdc-6d8456cc4eb7)

**Comment by cleong110** [comment]
@SalsabilRefaei that feature was introduced in Python 3.9, perhaps that's the issue? Also we could probably discuss that in a different thread, this error doesn't seem related to the "command not found" one in this thread

Article about removesuffix: https://www.geeksforgeeks.org/python-string-removesuffix/

**Comment by cleong110** [comment]
I see in the image that your Python version is 3.7, so that's probably it.

**Comment by cleong110** [comment]
Tried testing/replicating, but Python 3.7 is so old that I can't figure out how to install it in Google Colab at all, sorry

**Comment by cleong110** [comment]
Nevermind, got it running. See https://colab.research.google.com/drive/18vwjnjM29EAb3KaH5Y7wq3sxBDys-HCE?usp=sharing. That was indeed the issue. 

I recommend looking into something like virtualenv aor miniconda so you can switch Python versions easily. https://docs.conda.io/projects/miniconda/en/latest/index.html

**Comment by cleong110** [comment]
@SalsabilRefaei I am curious how you installed `pose-format`? Because I would have expected pip to check the Python version and make an error

**Comment by SalsabilRefaei** [comment]
> @SalsabilRefaei I am curious how you installed `pose-format`? Because I would have expected pip to check the Python version and make an error

 I used pip .I did not have any problem, it works fine.

**Comment by cleong110** [comment]
Ah, then perhaps we should add a check to prevent it from installing without Python 3.9 or later.
