### ISSUE TITLE
Transparent background for GIF

### ISSUE THREAD

**Issue by bipinkrish** [sign-language-processing/pose#82]
I would be good idea to save gif with transparent background by default then white background so it suits for most of the users.

Just need to set `alpha` channel value `0` here

* https://github.com/sign-language-processing/pose/blob/master/src/python/pose_format/pose_visualizer.py#L113

* https://github.com/sign-language-processing/pose/blob/master/src/python/pose_format/pose_visualizer.py#L231

**Comment by AmitMY** [comment]
I agree that it would be best to save gifs with transparency.
I'll be honest - I didn't know that the GIF format even supported transparency, but just learned that it is only partial:
> the GIF format doesn't support partial (alpha-channel) transparency

I don't have time to look into this in the next week or so, so I invite you to contribute this modification if you want it soon.

**Comment by bipinkrish** [comment]
I tried to do it, I got transparent background but hand movements become clustered and it wasn't smooth, I cant figure out why would background color change affects the hand motion.

**Comment by AmitMY** [comment]
If you create a PR, and specify the issue (with an example GIF), I might be able to look at it faster

**Comment by bipinkrish** [comment]
sure

**Comment by bipinkrish** [comment]
I will soon open a PR to show the changes but this is the result

Expected:

![pose-unscreen](https://github.com/sign-language-processing/pose/assets/87369440/aae693a9-b3ec-4278-b14d-c7fa2cc0d688)

Actuall:

![pose-transparent](https://github.com/sign-language-processing/pose/assets/87369440/5a7cf4e6-d275-495c-bf5e-8a55682dccc7)

**Comment by AmitMY** [comment]
Ah! so the issue is probably this one https://stackoverflow.com/questions/60948028/python-pillow-transparent-gif-isnt-working

> You have not specified the disposal parameter of Image.save(). This parameter controls how the previous frame is disposed in relation to the background. If unspecified, the previous frame "lingers" into the next frame(s). Adding disposal=2 should resolve that particular issue.

**Comment by bipinkrish** [comment]
Yeah according to [this](https://github.com/python-pillow/Pillow/issues/6115#issuecomment-1061858535) GIF has border problems but APNG doesn't have that

GIF:

![pose.gif](https://github.com/sign-language-processing/pose/assets/87369440/31a060d2-f17f-42a0-b546-1099867899a6)

PNG : 

![pose.png](https://github.com/sign-language-processing/pose/assets/87369440/0276d6ad-a34b-470a-b52a-39c3e02b285d)

Should I stick with PNG?

**Comment by AmitMY** [comment]
Glad to see you got it working.
Personally, for a moving video, I would choose `webm`. If you can't use a video, `webp` would be a good alternative.

**Comment by AmitMY** [comment]
Thanks for solving your issue!
