### ISSUE TITLE
Face is not converted

### ISSUE THREAD

**Issue by m7mdhka** [sign-language-processing/pose#91]
Hello,
I've try to convert OpenPose to Holistic, but the face is not shown in the holistic when I've tried to converting.
![image](https://github.com/sign-language-processing/pose/assets/43252562/10774f00-9b29-4527-9dd5-9b9ede7588e9)
![image](https://github.com/sign-language-processing/pose/assets/43252562/69e91798-422e-45c8-9540-181ea599babb)

This is my code:
```
conv_holistic = convert_pose(original_pose, holistic_components("XYZC", 10))
```

**Comment by m7mdhka** [comment]
If can't be fixed how can I make a fake face with the converted pose?!

**Comment by AmitMY** [comment]
Here is the utility responsible for converting the pose from OpenPose to Holistic and back:
https://github.com/sign-language-processing/pose/blob/master/src/python/pose_format/utils/pose_converter.py

You can see `LEFT_HAND_MAP` and `RIGHT_HAND_MAP` are straight forward.
`BODY_MAP` is a custom mapping.
If you would like to add a `FACE_MAP`, that would be highly appreciated - It should include all 69 face contour points from:
![image](https://github.com/sign-language-processing/pose/assets/5757359/0bda5021-9189-4e86-b01b-c5c985eaba6e)

and map to mediapipe face mesh contour points (here, they are connected by lines)
![image](https://github.com/sign-language-processing/pose/assets/5757359/b5f9b876-a834-4ac7-aca2-6ec9222a5ec6)

To see their name more clearly, look at this picture:
![image](https://github.com/sign-language-processing/pose/assets/5757359/827ded2b-ff8b-4412-82ef-966c74b94713)

**Comment by m7mdhka** [comment]
@AmitMY Thank you, 
I see the code, and I found more [clearly image for MediaPipe](https://storage.googleapis.com/mediapipe-assets/documentation/mediapipe_face_landmark_fullsize.png).
I tried to make a Map for border but there no results appear.
This is my code:

```
FACE_MAP = [
    # face border
    (("face_keypoints_2d", "FB_0"), ("FACE_LANDMARKS", 127)),
    (("face_keypoints_2d", "FB_1"), ("FACE_LANDMARKS", 234)),
    (("face_keypoints_2d", "FB_2"), ("FACE_LANDMARKS", 93)),
    (("face_keypoints_2d", "FB_3"), ("FACE_LANDMARKS", 132)),
    (("face_keypoints_2d", "FB_4"), ("FACE_LANDMARKS", 58)),
    (("face_keypoints_2d", "FB_5"), ("FACE_LANDMARKS", 172)),
    (("face_keypoints_2d", "FB_6"), ("FACE_LANDMARKS", 136)),
    (("face_keypoints_2d", "FB_7"), ("FACE_LANDMARKS", 149)),
    (("face_keypoints_2d", "FB_8"), ("FACE_LANDMARKS", 152)),
    (("face_keypoints_2d", "FB_9"), ("FACE_LANDMARKS", 378)),
    (("face_keypoints_2d", "FB_10"), ("FACE_LANDMARKS", 365)),
    (("face_keypoints_2d", "FB_11"), ("FACE_LANDMARKS", 397)),
    (("face_keypoints_2d", "FB_12"), ("FACE_LANDMARKS", 288)),
    (("face_keypoints_2d", "FB_13"), ("FACE_LANDMARKS", 361)),
    (("face_keypoints_2d", "FB_14"), ("FACE_LANDMARKS", 323)),
    (("face_keypoints_2d", "FB_15"), ("FACE_LANDMARKS", 454)),
    (("face_keypoints_2d", "FB_16"), ("FACE_LANDMARKS", 356)),
]
```

note that I add it to the `POSES_MAP`.

**Comment by m7mdhka** [comment]
@AmitMY it's solved by use `string` for `FACE_LANDMARKS` points.
Thank you.


![b0a88b70-6c10-4d6f-af2d-b829b9c9c922](https://github.com/sign-language-processing/pose/assets/43252562/6a0898c0-4c59-4e5b-b78a-1f0b4172c26e)

**Comment by m7mdhka** [comment]
I will put the best `FACE_MAP` I found here as soon as possible.

**Comment by AmitMY** [comment]
Glad you got it to work. Feel free to contribute a pull request when done :)

**Comment by AmitMY** [comment]
If it is of any help, here are all of the contour points for holistic:
```ts
    face_contours = [
        '0', '7', '10', '13', '14', '17', '21', '33', '37', '39', '40', '46', '52', '53', '54', '55', '58', '61', '63',
        '65', '66', '67', '70', '78', '80', '81', '82', '84', '87', '88', '91', '93', '95', '103', '105', '107', '109',
        '127', '132', '133', '136', '144', '145', '146', '148', '149', '150', '152', '153', '154', '155', '157', '158',
        '159', '160', '161', '162', '163', '172', '173', '176', '178', '181', '185', '191', '234', '246', '249', '251',
        '263', '267', '269', '270', '276', '282', '283', '284', '285', '288', '291', '293', '295', '296', '297', '300',
        '308', '310', '311', '312', '314', '317', '318', '321', '323', '324', '332', '334', '336', '338', '356', '361',
        '362', '365', '373', '374', '375', '377', '378', '379', '380', '381', '382', '384', '385', '386', '387', '388',
        '389', '390', '397', '398', '400', '402', '405', '409', '415', '454', '466'
    ]
    ```
    If you specify all of these, it will look very nice.
    
    This is missing the nose, which you could add afterwards

**Comment by m7mdhka** [comment]
What do you think about this results?
![image](https://github.com/sign-language-processing/pose/assets/43252562/e2b8453f-f29f-40e4-8364-49e8a5409e0d)

Is it good t pull request?

**Comment by AmitMY** [comment]
that is damn impressive.
of course, this is great for a pull request! if there are any more things to do about it, we can leave it for future users to refine
