### ISSUE TITLE
RuntimeError: The size of tensor a (1728) must match the size of tensor b (1152) at non-singleton dimension 2

### ISSUE THREAD

**Issue by rem0g** [sign-language-processing/pose#94]
I am trying to run normalisation on the .pose format using the example code, but I am getting this error: 

```
python3 pose_to_siren_to_pose.py 
Poses loaded
/home/gomer/.local/lib/python3.10/site-packages/pose_format/utils/siren.py:216: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:261.)
  self.points = torch.tensor([p.flatten() for p in np.array(pose.body.data)], dtype=torch.float32)
Traceback (most recent call last):
  File "/home/gomer/signbank/pose_to_siren_to_pose.py", line 69, in <module>
    p = pose_to_siren_to_pose(p)
  File "/home/gomer/signbank/pose_to_siren_to_pose.py", line 49, in pose_to_siren_to_pose
    net = siren.get_pose_siren(p, total_steps=3000, steps_til_summary=100, learning_rate=1e-4, cuda=True)
  File "/home/gomer/.local/lib/python3.10/site-packages/pose_format/utils/siren.py", line 328, in get_pose_siren
    loss = masked_mse_loss(model_output, ground_truth, confidence)
  File "/home/gomer/.local/lib/python3.10/site-packages/pose_format/utils/siren.py", line 270, in masked_mse_loss
    return (sq_error * confidence).mean()
RuntimeError: The size of tensor a (1728) must match the size of tensor b (1152) at non-singleton dimension 2
```

I am using Python version 3.10.12

**Comment by AmitMY** [comment]
The siren example was not maintained for a long while.
What are you trying to achieve with it?
What kind of normalization are you trying to perform?

**Comment by rem0g** [comment]
I am fairly new to normalisation, i assumed it is the standard procedure to normalise the pose. 

Is there an example that does not use the Siren module? Should i try to use the one at the README?

**Comment by rem0g** [comment]
We are trying to run segmentation on our NGT Corpus files, so to improve the results I thought it would be a good idea to run normalisation on the hands. 

I discovered recently at the segmentation repo there is already normalization build in the model; so i am going to try that and try to train model on NGT Corpus dataset with 3D Hand normalization and see if there is improvement in results. 

Please correct me if im wrong, otherwise this issue can be closed (for me).

**Comment by AmitMY** [comment]
For the segmentation model, here is the exact normalization used:
https://github.com/sign-language-processing/segmentation/blob/main/sign_language_segmentation/bin.py#L28-L43

No sirens involved :)
If you are using the E1 model, it does not require 3D hand normalization, and if you use the E4 model, it does.
