### ISSUE TITLE
Plausible memory leak when processing numerous videos, some of which are corrupted

### ISSUE THREAD

**Issue by clementReverdy** [sign-language-processing/pose#96]
Hello, first of all I want you to thank you for your works (in particular those about sign languages).

My problem is perhaps a bit specific as I use your library to process ~44k videos with various characteristics using Mediapipe Holistic. Most of these are OK but a minority can be broken. I essentially apply load_holistic(...) inside a loop with a try...except to be resistant to these corrupted files. The process works fine except that I've seen a memory leak which eventually saturate the RAM.

The problem comes from the process_holistic(...) function in src/python/pose_format/utils/holistic.py because when an exception occurs, the process is interrupted without closing holistic.

As there are several reasons why a video can be corrupted and the means of detecting it can be tedious (perhaps ffmpeg + popen would do the trick), I thought it simpler to solve this problem locally by editing the src/python/pose_format/utils/holistic.py file as follows:

```py
def process_holistic(frames: list,
                     fps: float,
                     w: int,
                     h: int,
                     kinect=None,
                     progress=False,
                     additional_face_points=0,
                     additional_holistic_config={}) -> NumPyPoseBody:
    """
    process frames using holistic model from mediapipe

    Parameters
    ----------
    frames : list
        List of frames to be processed
    fps : float
        Frames per second
    w : int
        Frame width
    h : int
        Frame height.
    kinect : object, optional
        Kinect depth data.
    progress : bool, optional
        If True, show the progress bar.
    additional_face_points : int, optional
        Additional face landmarks (points)
    additional_holistic_config : dict, optional
        Additional configurations for holistic model

    Returns
    -------
    NumPyPoseBody
        Processed pose data
    """
    holistic = mp_holistic.Holistic(static_image_mode=False, **additional_holistic_config)

    datas = []
    confs = []
	
	try:
		for i, frame in enumerate(tqdm(frames, disable=not progress)):
			results = holistic.process(frame)

			body_data, body_confidence = body_points(results.pose_landmarks, w, h, 33)
			face_data, face_confidence = component_points(results.face_landmarks, w, h,
														  FACE_POINTS_NUM(additional_face_points))
			lh_data, lh_confidence = component_points(results.left_hand_landmarks, w, h, 21)
			rh_data, rh_confidence = component_points(results.right_hand_landmarks, w, h, 21)
			body_world_data, body_world_confidence = body_points(results.pose_world_landmarks, w, h, 33)

			data = np.concatenate([body_data, face_data, lh_data, rh_data, body_world_data])
			conf = np.concatenate([body_confidence, face_confidence, lh_confidence, rh_confidence, body_world_confidence])

			if kinect is not None:
				kinect_depth = []
				for x, y, z in np.array(data, dtype="int32"):
					if 0 < x < w and 0 < y < h:
						kinect_depth.append(kinect[i, y, x, 0])
					else:
						kinect_depth.append(0)

				kinect_vec = np.expand_dims(np.array(kinect_depth), axis=-1)
				data = np.concatenate([data, kinect_vec], axis=-1)

			datas.append(data)
			confs.append(conf)

		pose_body_data = np.expand_dims(np.stack(datas), axis=1)
		pose_body_conf = np.expand_dims(np.stack(confs), axis=1)

		holistic.close()
	except Exception as e:
		holistic.close()
		raise e

    return NumPyPoseBody(data=pose_body_data, confidence=pose_body_conf, fps=fps)
```
This solution worked for me.

Thank you all very much. Yours sincerely

**Comment by AmitMY** [comment]
I would have assumed that if the video is broken, it will fail before `process_holistic` since you need to acquire the frames.
In any case, I have implemented a similar solution to yours, using a `finally` statement
https://github.com/sign-language-processing/pose/commit/d0ac8f47ad53c45118a4d9e078625c6a2aef2ce6

**Comment by clementReverdy** [comment]
I would also have assumed that and my first attempt to check the integrity of the videos was to check cv2.VideoCapture. In some case the medias doesn't open at all and it is possible to check it with cap.isOpened() but in other cases it does open and errors are thrown later. 

Anyway, thank you for your fix. I already downloaded it and tested it and everything is fine. Have a nice day ! : - )
